[package]
name = "yarner-fold-code"
version = "0.1.0"
authors = ["Martin Lange <martin_lange_@gmx.net>"]
edition = "2018"

[dependencies]
yarner-lib = { git = "https://github.com/mlange-42/yarner.git", rev = "54488e6" }
